# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
tls:

  options:
    default:
      minVersion: "VersionTLS13"
      # {{ if or ( env "TRAEFIK_TLS_RESOLVER" ) ( env "TRAEFIK_TLS_CERT" ) }}
      sniStrict: true
      # {{ end }}
      # {{ if env "TRAEFIK_MTLS_CERTS" }}
      clientAuth:
        clientAuthType: 'RequireAndVerifyClientCert'
        caFiles:
          # {{ range $i, $v := env "TRAEFIK_MTLS_CERTS" | splitList "\n" }}
          - '{{ $v }}'
          # {{ end }}
      # {{ end }}

  # {{ if env "TRAEFIK_TLS_CERT" }}
  certificates:
    - keyFile: '{{ env "TRAEFIK_TLS_KEY" }}'
      certFile: '{{ env "TRAEFIK_TLS_CERT" }}'
  # {{ end }}

http:

  routers:
    https-redirect:
      rule: 'PathPrefix(`/`)'
      entryPoints: ["http"]
      middlewares: ["https-redirect"]
      service: "noop@internal"
    shiny:
      rule: 'Host(`{{ env "DOMAIN" }}`)'
      entryPoints: ["https"]
      middlewares: ["security-headers"]
      service: "shiny"
      tls: { certResolver: '{{ env "TRAEFIK_TLS_RESOLVER" }}' }

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: "https"
        permanent: true
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        referrerPolicy: "strict-origin"
        contentTypeNosniff: true
        permissionsPolicy: >-
          accelerometer=(),
          camera=(),
          geolocation=(),
          gyroscope=(),
          magnetometer=(),
          microphone=(),
          midi=(),
          payment=(),
          usb=()
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""

  services:
    shiny:
      loadBalancer:
        servers:
          - url: "http://shiny-server:3838"

tcp:

  routers:
    postgres:
      rule: 'HostSNI(`*`)'
      entryPoints: ["postgres"]
      service: "postgres"

  services:
    postgres:
      loadBalancer:
        servers:
          - address: "postgres:5432"
