# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      # {{ if or ( env "TRAEFIK_TLS_RESOLVER" ) ( env "TRAEFIK_TLS_CERT" ) }}
      sniStrict: true
      # {{ end }}
  # {{ if env "TRAEFIK_TLS_CERT" }}
  certificates:
    - keyFile: '{{ env "TRAEFIK_TLS_KEY" }}'
      certFile: '{{ env "TRAEFIK_TLS_CERT" }}'
  # {{ end }}
http:
  routers:
    keycloak:
      rule: 'Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/keycloak`)'
      entryPoints: ["https", "proxy"]
      middlewares: ["security-headers", "keycloak-security-headers"]
      service: "keycloak"
      tls: { certResolver: '{{ env "TRAEFIK_TLS_RESOLVER" }}' }
    shiny:
      rule: 'Host(`{{ env "DOMAIN" }}`)'
      entryPoints: ["https", "proxy"]
      middlewares: ["security-headers"]
      service: "shiny"
      tls: { certResolver: '{{ env "TRAEFIK_TLS_RESOLVER" }}' }
    # {{ if env "TRAEFIK_API_BASIC_AUTH" }}
    dashboard:
      rule: 'PathPrefix(`/api`) || PathPrefix(`/dashboard`)'
      entryPoints: ["traefik"]
      middlewares: ["dashboard-auth"]
      service: "api@internal"
    # {{ end }}
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        referrerPolicy: "strict-origin"
        contentTypeNosniff: true
        permissionsPolicy: >-
          accelerometer=(),
          camera=(),
          geolocation=(),
          gyroscope=(),
          magnetometer=(),
          microphone=(),
          midi=(),
          payment=(),
          usb=()
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
    keycloak-security-headers:
      headers:
        contentSecurityPolicy: >-
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval';
          style-src 'self' 'unsafe-inline';
          img-src 'self' blob: data:;
    # {{ if env "TRAEFIK_API_BASIC_AUTH" }}
    dashboard-auth:
      basicAuth:
        users: ['{{ env "TRAEFIK_API_BASIC_AUTH" }}']
    # {{ end }}
  services:
    keycloak:
      loadBalancer:
        servers:
          - url: "http://shiny-keycloak:8080"
    shiny:
      loadBalancer:
        servers:
          - url: "http://shiny-server:3838"
tcp:
  routers:
    postgres:
      rule: 'HostSNI(`*`)'
      entryPoints: ["postgres"]
      service: "postgres"
  services:
    postgres:
      loadBalancer:
        servers:
          - address: "shiny-postgres:5432"

