# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
# {{ if env "TRAEFIK_PROXY_DOMAINS" }}
tcp:
  routers:
    # {{ range $i, $v := env "TRAEFIK_PROXY_DOMAINS" | splitList "\n" }}
    proxy-{{ $v }}:
      rule: 'HostSNI(`{{ $v }}`)'
      entryPoints: ["proxy"]
      service: "proxy-{{ $v }}"
      tls:
        passthrough: true
    # {{ end }}
  services:
    # {{ range $i, $v := env "TRAEFIK_PROXY_DOMAINS" | splitList "\n" }}
    proxy-{{ $v }}:
      loadBalancer:
        servers:
          - address: "{{ $v }}:443"
    # {{ end }}
# {{ end }}
